version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:860061945305:task-definition/avitask:1"
        LoadBalancerInfo:
          ContainerName: "packageanddelivery"
          ContainerPort: "9003"
        PlatformVersion: "LATEST"
